name: DejansTollesPlugin
main: blaues.myplugin.MainClass
version: 1
autor: BlauesBIld
api-version: 1.15

commands:
  start:
    description: starts the game
    usage: "Usage: /<command>"
  rlPlayer:
    description: reloads the list of player
    usage: "Usage: /<command>"